version: "3.5"

services:
  jenkins:
    container_name: jenkins-container-cert
    image: elvbisdocker/jenkinsjdk17docker:v0
    build:
      context: jenkins_docker
    ports:
      - 9000:8080
    user: "root:jenkins"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network_cicd
  sonarqube:
    image: sonarqube:lts-community
    security_opt:
    - seccomp:unconfined
    container_name: sonarqube
    ports:
    - 9010:9000
    - 5431:5431
    environment:
    - SONARQUBE_JDBC_URL=jdbc:jdbc:postgresql://{ip:port}/sonar
    - SONARQUBE_JDBC_USERNAME={user}
    - SONARQUBE_JDBC_PASSWORD={pass}
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    - sonarqube_common:/opt/sonarqube/lib/common
    networks:
      - network_cicd
volumes:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins:
    sonarqube_common:
networks:
  network_cicd:
    name: network_cicd
